name: "Alembic Migration Checker"
author: "DevGlitch"
description: "Automate Alembic database migration checks for PostgreSQL, MySQL, and SQLite in CI/CD workflows"
branding:
  icon: "check-circle"
  color: "blue"
inputs:
  db_url:
    description: "Database URL. Alternative to specifying individual database connection parameters. Default: ''"
    required: false
    default: ""
  db_type:
    description: "Database type. Supported types are 'postgresql', 'mysql', and 'sqlite'. Default: 'postgresql'"
    required: false
    default: "postgresql"
  db_host:
    description: "Database host"
    required: false
    default: ""
  db_port:
    description: "Database port. Not required for SQLite. Default: 5432."
    required: false
    default: '5432'
  db_user:
    description: "Database user. Not required for SQLite."
    required: false
    default: ""
  db_password:
    description: "Database password. Not required for SQLite."
    required: false
    default: ""
  db_name:
    description: "Database name. Not required for SQLite."
    required: true
  migrations_path:
    description: "Path to the Alembic migrations folder. Default: './migrations/'"
    required: false
    default: "./migrations/"
  alembic_version_table_schema:
    description: "Schema name for the alembic_version table. Default: 'public'"
    required: false
    default: "public"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.db_url }}
    - ${{ inputs.db_type }}
    - ${{ inputs.db_host }}
    - ${{ inputs.db_port }}
    - ${{ inputs.db_user }}
    - ${{ inputs.db_password }}
    - ${{ inputs.db_name }}
    - ${{ inputs.alembic_version_table_schema }}
    - ${{ inputs.migrations_path }}
